core/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views  import   LogoutView


app_name = "core"

urlpatterns = [
    # func
    path("change_lang/", views.change_lang,                                                 name="change_lang"     ),
    # auth
    path("signup/",      views.signup,                                                      name="signup"          ),
    path("login/",       views.LoginViewSec.as_view(template_name="pages/login.html"),      name="login"           ),
    path("signup/<str:lang>/", views.signup,                                                name="signup"          ),
    path("login/<str:lang>/",  views.LoginViewSec.as_view(template_name="pages/login.html"),name="login"           ),
    path("logout/", LogoutView.as_view(),                                                   name="logout"          ),
    # landing
    path("", views.landing      ,                                                           name="landing"         ),
    path("welcome/<str:lang>/", views.landing      ,                                        name="landing"         ),
    # courses
        # Workshops

    
    # payment
    path("payment/<str:lang>/", views.payment, name="payment"),

    path("payment/", views.payment, name="payment"),
    path("meetups/<str:lang>/", views.meetup, name="meetups"),
    path("meetups/", views.meetup, name="meetups"),
    path("meetups/<str:lang>/<int:pk>/", views.meetup_detail, name="meetup"),
    path("meetups/<str:lang>/", views.meetup_detail, name="meetup"),



    path("send_test_email/", views.send_test_email, name="send_test_email"),


    path("summits/<str:lang>/", views.summit, name="summit"),
    path("summits/", views.summit, name="summit"),
    path("summits/<str:lang>/<int:pk>/", views.summit_detail, name="summit_detail"),
    path("summits/<str:lang>/", views.summit_detail, name="summit_detail"),

    path("speakers/<str:lang>/<int:pk>/", views.speaker, name="speaker"),
    path("speakers/<str:lang>/", views.speaker, name="speaker"),
    path("speakers/", views.speaker, name="speaker"),


    path("check_qr_valid_or_not/<str:uuid>/", views.check_qr_valid_or_not, name="check_qr_valid_or_not"),
    path("check_qr_valid_or_not/", views.check_qr_valid_or_not, name="check_qr_valid_or_not"),

]

courses/urls.py
from django.urls import path
from . import views

app_name = "courses"

urlpatterns = [
    path("courses/<str:lang>/", views.courses_categories_list, name="courses_categories"),
    path("courses/", views.courses_categories_list, name="courses_categories"),
    #
    #course detailes 
    path("courses/<str:lang>/<int:pk>/", views.course_detail, name="course_detail"),
    # video details

    path("courses/<str:lang>/<str:course>/ep/", views.video_detail,                        name="video_detail"),
    path("courses/<str:lang>/<str:course>/ep/<int:pk>/", views.video_detail,                        name="video_detail"),

    path("courses/<str:lang>/<str:course>/", views.course_list_view,                        name="couese_list_view"),
    path("instructor/<str:lang>/<int:pk>/", views.instructor_detail, name="instructor_detail"),
    path("instructor/<str:lang>/", views.instructor_detail, name="instructor_detail"),
    path("instructor/", views.instructor_detail, name="instructor_detail"),

]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
path('admin/', admin.site.urls),
path('', include('core.urls')),
path('', include('courses.urls')),
path('', include('workshops.urls')),
path('ckeditor5/', include('django_ckeditor_5.urls')), 

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

workshops/urls.py
from django.urls import path
from . import views

app_name = "workshops"
urlpatterns = [
    path("workshop/<str:lang>/", views.work_shop, name="workshop"),
    
]

core/models/workshops.py
from django.db import models
from datetime import datetime










class WorkShopsCategory(models.Model):
    name_en = models.CharField(max_length=100)
    name_ar= models.CharField(max_length=100)
    description_en = models.TextField()
    description_ar = models.TextField()
    banner         = models.ImageField(upload_to="workshopscategory_banner", null=True, blank=True)
    def  more(self):
        return "more"

    def __str__(self):
        return self.name_en




class WorkShops(models.Model):

    category = models.ForeignKey(WorkShopsCategory, on_delete=models.CASCADE)

    name_en = models.CharField(max_length=100)
    name_ar= models.CharField(max_length=100)

    description = models.TextField()

    start_date = models.DateField(default=datetime.now)
    end_date = models.DateField()
    location = models.CharField(max_length=100)
    
    def __str__(self):
        return self.name_en
    
    class Meta:
        verbose_name = "Workshops"
        verbose_name_plural = "Workshops"

core/views.py
from typing import Any
from django.shortcuts import render, redirect
from django.http      import HttpRequest, HttpResponse
from .form            import UserCustomForm, SummitForm
from django.urls      import reverse
from django.contrib.auth.views  import  LoginView
from .models                    import models
from random                     import choice
from django.core.mail import send_mail, EmailMultiAlternatives
from django.conf import settings
from django.utils.html import mark_safe, strip_tags
from django.contrib.messages import success ,error, info
from django.template.loader import render_to_string
from django_xhtml2pdf.utils import generate_pdf
from io import BytesIO
from xhtml2pdf import pisa
from django.template.loader import get_template
from django.db.models.query import QuerySet
import os
import time

# Landing Page Request Handle Function
def landing(req:HttpRequest, lang=None) -> HttpResponse:
    
    if  lang == None:
        return redirect(
            reverse("core:landing", args=["en"])
        )
    context = {

        "lang"     : lang,
        "active"   : "home"

    }
    c = choice([True, False])

    if c :

        return  render(req, "pages/landing1.html", context=context)
    
    return  render(req, "pages/landing2.html", context=context)




def signup(req:HttpRequest, lang=None) -> HttpResponse:

    if  lang == None:
        return redirect(
            reverse("core:signup", args=["en"])
        )

    if req.method == "POST":
        form = UserCustomForm(req.POST)

        if form.is_valid():
            form.save()

            return redirect(reverse("core:login"))

    form = UserCustomForm()

    context = {
        "form" : form,
        "lang" : lang
    }
    
    return  render(req, "pages/signup.html", context)


class LoginViewSec(LoginView):
    
    
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        x = super().get_context_data(**kwargs)
        x['lang'] = self.kwargs.get("lang", None)
        if  x['lang'] == None:
            return redirect(reverse("core:login", args=["en"]))

        return x
    
    def render_to_response(self, context: dict[str, Any], **response_kwargs: Any) -> HttpResponse:
        
        x = self.kwargs.get("lang", None)
        if  x == None:
            return redirect(
                reverse("core:login", args=["en"])
            )
        
        return super().render_to_response(context, **response_kwargs)
    
def change_lang(req:HttpRequest):
    
    url:str = req.META['HTTP_REFERER']
    
    if "en" in url:
        url = url.replace("en", "ar")
    elif "ar" in url:
        url = url.replace("ar", "en")

    return redirect(url)







def payment(req: HttpRequest, lang=None) -> HttpResponse :

    if lang == None:

        return redirect(reverse("payment", args=["en"]))

    context = {
        "lang" : lang         ,
    }
    return render(req, "pages/payment.html", context)






# instructor_detail.html





def meetup(req:HttpRequest, lang=None) -> HttpResponse:
    
    if  lang == None:
        
        return redirect(
            reverse("core:meetup", args=["en"])
        )
    
    meetups = models.Meetup.objects.all()
    context = {
        "lang" : lang         ,
        "active" : "meetups",
        "meetups" : meetups
    }
    return render(req, "pages/meetup.html", context)


def meetup_detail(req:HttpRequest, lang=None, pk:int=None) -> HttpResponse:
    
    if pk == None:
        return redirect(
            reverse("core:meetups", args=["en"])
        )
    if  lang == None:
        return redirect(
            reverse("core:meetup_detail", args=["en", pk])
        )
    
    meetup = models.Meetup.objects.get(pk=pk)
    meetups = meetups.exclude(pk=pk)
    context = {
        "lang"     : lang       ,
        "active"   : "meetups"  ,
        "meetup"   : meetup ,
        "others"   : meetups  ,
    }
    return  render(req, "pages/meetup_detail.html", context=context)

def render_to_pdf(template, context):
   template = get_template(template)
   html  = template.render(context)
   result = BytesIO()
   pdf = pisa.pisaDocument(BytesIO(html.encode("UTF-8")), result)
   if not pdf.err:
       return HttpResponse(result.getvalue(), content_type='application/pdf')
   return None

# ###############################################################################
def send_them_email(request:HttpRequest, queryset:QuerySet[models.SummitTicket]):
    # msg = models.Messages.objects.first()
    counter = 0
    for obj in queryset:

        try:
            the_code = models.QrcodeForTicket.objects.get(summitticket=obj)

            context = {
                "url_my_image" : settings.SITE_DOMAIN + the_code.qrcode.url,
                # "msg" : msg,
                "his_name" : obj.name,
            }   
            
            subject =  f"Welcome to {obj.summit.name_en}"
            if obj.ticket_type == "S" or obj.ticket_type == None or obj.ticket_type != "V":
                    context["ticket_type"] =  settings.SITE_DOMAIN +  "/static/image/standard_ticket.jpeg" 

                    html_message = render_to_string('emails/summit_temp.html', context)
            elif obj.ticket_type == "V":
                context["ticket_type"] =  settings.SITE_DOMAIN +  "/static/image/Vip_ticket.jpeg"
                html_message = render_to_string('emails/summit_temp_vip.html', context)

            plaintext_message = strip_tags(html_message)
            from_email = settings.EMAIL_HOST_USER
            message = EmailMultiAlternatives(subject=subject , body=plaintext_message, from_email= from_email, to= [obj.email])  
            message.attach_alternative(html_message, "text/html")
            message.send() 
            obj.sended_mail = True
            obj.save()
            counter += 1
            time.sleep(1)
            if counter == 10:
                time.sleep(10)
                counter = 0
        except:
            info(request, f"{obj.email} is not a valid email")

def send_test_email(request:HttpRequest):
    # 
    the_message = request.GET.get('hiddenMessage')
    the_tiket = request.GET.get('pk')
    ticket_email = request.GET.get('hiddenEmail')
    print(the_tiket)
    qrcode = models.QrcodeForTicket.objects.get(pk=int(the_tiket))
    summitticket = models.SummitTicket.objects.filter(email=ticket_email)
    summitticket = summitticket[0]
    summitticket.sended_mail = True
    summitticket.save()
    message = models.Messages.objects.get(pk=int(the_message))
    message = mark_safe(message.Text)

    subject = f'Ticket for {summitticket.summit.name_en}'
    

    context = {
        "url_my_image" : settings.SITE_DOMAIN + qrcode.qrcode.url,
        "msg" : message
    }
    html_message = render_to_string('emails/summit_temp.html', context)
    # context["imgagin"] = True
    # pdf          = generate_pdf('emails/summit_temp.html', context=context)
    # path = os.path.join(r"F:\ticket.pdf")
    # with open(path, 'wb') as f:
    #     f.write(pdf.getbuffer().tobytes())

    # context["pdf"] = pdf
    # html_message = render_to_string('emails/summit_temp.html', context)
    # print(pdf.__sizeof__())
    # recipient_list = ['bettercallguts@gmail.com']
    from_email = settings.EMAIL_HOST_USER
    plaintext_message = strip_tags(html_message)
    message = EmailMultiAlternatives(subject=subject,body= plaintext_message, from_email= from_email, to= [ticket_email])  
    
    # message.attach('Ticket.pdf', pdf.read(), 'application/pdf')
    # message.attach_file(path)
    message.attach_alternative(html_message, "text/html")
    message.send()
    success(request, "Email sent successfully")

    # send_mail(subject,mark_safe( message), from_email, recipient_list, fail_silently=True)
    return redirect(request.META['HTTP_REFERER'])



def summit(req:HttpRequest, lang=None) -> HttpResponse:
    if req.method == "POST":
        temp = {}
        temp['csrfmiddlewaretoken'] =req.POST.get('csrfmiddlewaretoken')
        temp['summit'] = req.POST.get('summit_id')
        temp['name'] = req.POST.get('username')
        temp['email'] = req.POST.get('email')
        temp['phone_number'] = req.POST.get('phone_number')
        temp['job_title'] = req.POST.get('job_title')
        if req.user.is_authenticated:
            temp['user'] = req.user

        print(temp)
        form = SummitForm(temp)

        if form.is_valid():
            form.save()
            return redirect(reverse("core:summit"))
        else:
            print(form.errors)

    if  lang == None:
        
        return redirect(
            reverse("core:summit", args=["en"])
        )
    
    summits = models.Summit.objects.all()
    speaker = models.Speakers.objects.all()
    context = {
        "lang" : lang         ,
        "active" : "summits",
        "summits" : summits,
        "speakers" : speaker,
    }
    return render(req, "pages/summit.html", context)


def summit_detail(req:HttpRequest, lang=None, pk:int=None) -> HttpResponse:
    
    if pk == None:
        return redirect(
            reverse("core:summit", args=["en"])
        )
    if  lang == None:
        return redirect(
            reverse("core:summit_detail", args=["en", pk])
        )
    
    summit = models.Summit.objects.get(pk=pk)
    summits = summits.exclude(pk=pk)
    context = {
        "lang"     : lang       ,
        "active"   : "summits"  ,
        "summit"   : summit ,
        "others"   : summits  ,
    }
    return  render(req, "pages/summit_detail.html", context=context)


def summit_ticket(req:HttpRequest, lang=None, pk:int=None) -> HttpResponse:
    
    if pk == None:
        return redirect(
            reverse("core:summit_ticket", args=["en"])
        )
    if  lang == None:
        return redirect(
            reverse("core:summit_ticket", args=["en", pk])
        )
    
    summit = models.Summit.objects.get(pk=pk)
    summits = summits.exclude(pk=pk)
    context = {
        "lang"     : lang       ,

core/templates/components/navbar.html
{% load static %}

{% comment %} 
<div class="navbar" id="Navbar" style="z-index: 1000;">
    <!-- ACT Button -->
    {% if not user.is_authenticated %}
    <a href="{% url 'core:login' lang %}" class="navbar__act-button">

        {% if lang == "en" %}
        Login
        {% elif lang == "ar" %}

        تسجيل الدخول
        {% endif %}
    </a>
    {% else %}
    <form action="{% url 'core:logout'  %}" method="post">
        {% csrf_token %}
        <input 
        style="color: var(--white);outline:none; background:rgba(0,0,0,1)"
        type="submit" class="navbar__act-button" value="{% if lang == "en" %}Logout{% elif lang == "ar" %}تسجيل الخروج{% endif %}">
    </form>
    {% endif %}
    

    <ul class="navbar__links-list" dir="rtl"  style="z-index: 1000;">
        <li class="{% if active == 'home' %}active{% endif %}">
            <a href="/" dir="rtl">
            {% if lang == "ar"  %}
            الرئيسية
            {% elif lang == "en" %}
            Home
            {% endif %}
            </a>

        </li>
        <li>
            <a href="/" dir="rtl">
            {% if lang == "ar" %}
                عن Thoth
            {% elif lang == "en" %}
                About Thoth
            {% endif %}
            </a>
        </li>
            <li class="{% if active == 'courses' %}active{% endif %}">
            <a href="{% url 'courses:courses_categories' lang %}" class="" dir="rtl">
            {% if lang == "ar" %}
            دورات تدريبية
            {% elif lang == "en" %}
                Courses
            {% endif %}
            </a>
            
        </li>
        <li class="{% if active == 'meetups' %}active{% endif %}">
            <a href="{% url "core:meetups" lang %}" dir="rtl">
            
                {% if lang == "ar" %}
                لقاءات
                
                {% elif lang == "en" %}
                Meetups
                {% endif %}
            
            </a>
        </li>
        <li class="{% if active == 'summits' %}active{% endif %}">
            <a href="{% url "core:summit" lang %}" dir="rtl">
            
                {% if lang == "ar" %}
                مؤتمرات
                
                {% elif lang == "en" %}
                Summits
                {% endif %}
            
            </a>
        </li>
        <li class="{% if active == 'workshops' %}active{% endif %}" />
            <a href="{% url 'workshops:workshop' lang %}" dir="rtl">
            
                {% if lang == "ar" %}
                ورشة عمل
                
                {% elif lang == "en" %}
                Workshops
                {% endif %}
            
            </a>
        </li>
       
        <li>
            <a href="/" dir="rtl">
            {% if lang == "ar" %}
            B2B
            {% elif lang == "en" %}
            B2B
            {% endif %}    
            
            </a>
        </li>
        <li dir="ltr" >
            {% if lang == "ar" %}
            <a href="{% url 'core:change_lang' %}" dir="ltr">
                English?
            </a>
            {% elif lang == "en" %}
            
            <a href="{% url 'core:change_lang' %}" dir="ltr">
                العربية؟
            </a>
            {% endif %}    
            
        </li>

    </ul>

    <!-- Logo -->
    
    <a href="/" >
    <div class="logo">
        <div class="logo__image">
            <img src="{% static  'image/logo_sm.png' %}" alt="Thoth Logo" />
        </div>
        <div class="logo__text">
            Thoth<br />Business<br />Hub
        </div>
    </div>  
    </a>
</div>


 {% endcomment %}

 <div class="ftco-section navbarr" id="Navbar" >
    
    <div class="container">
        <nav class="navbar navbar-expand-lg ftco_navbar " id="ftco-navbar">
        <div class="container">
            <a class="navbar-brand" href="/">
                <div class="logo">
                    <div class="logo__image">
                        <img src="{% static  'image/logo_sm.png' %}" alt="Thoth Logo" />
                    </div>
                    <div class="logo__text">
                        Thoth<br />Business<br />Hub
                    </div>
                </div>  
                </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="fa fa-bars"></span> 
          </button>
          <div class="collapse navbar-collapse" id="ftco-nav">
            <ul  dir="rtl"  class="navbar-nav ml-auto mr-md-3 navbar__links-list">
                    <li class="nav-item {% if active == 'home' %}active{% endif %}">                                                                                            
                <li class="nav-item {% if active == 'home' %}active{% endif %}">
                    <a href="/" dir="rtl" class="nav-link">
                    {% if lang == "ar"  %}
                    الرئيسية
                    {% elif lang == "en" %}
                    Home
                    {% endif %}
                    </a>
        
                </li>
                <li class="nav-item {% if active == 'about_thoth' %}active{% endif %}">
                    <a class="nav-link" href="/" dir="rtl">
                    {% if lang == "ar" %}
                        عن Thoth
                    {% elif lang == "en" %}
                        About Thoth
                    {% endif %}
                    </a>
                </li>  
                <li class="nav-item {% if active == 'courses' %}active{% endif %}">
                    <a class="nav-link" href="{% url 'courses:courses_categories' lang %}"  dir="rtl">
                    {% if lang == "ar" %}
                    دورات تدريبية
                    {% elif lang == "en" %}
                        Courses
                    {% endif %}
                    </a>
                    
                </li>            
                <li class="nav-item {% if active == 'meetups' %}active{% endif %}">
                    <a class="nav-link" href="{% url "core:meetups" lang %}" dir="rtl">
                    
                        {% if lang == "ar" %}
                        لقاءات
                        
                        {% elif lang == "en" %}
                        Meetups
                        {% endif %}
                    
                    </a>
                </li>


                <li class="nav-item {% if active == 'summits' %}active{% endif %}">
                    <a class="nav-link" href="{% url "core:summit" lang %}" dir="rtl">
                    
                        {% if lang == "ar" %}
                        مؤتمرات
                        
                        {% elif lang == "en" %}
                        Summits
                        {% endif %}
                    
                    </a>
                </li>
                <li class="nav-item {% if active == 'workshops' %}active{% endif %}" />
                <a class="nav-link" href="{% url 'workshops:workshop' lang %}" dir="rtl">
                
                    {% if lang == "ar" %}
                    ورشة عمل
                    
                    {% elif lang == "en" %}
                    Workshops
                    {% endif %}
                
                </a>
            </li>
            <li class="nav-item {% if active == 'b2b' %}active{% endif %}">
                <a class="nav-link" href="" dir="rtl">
                {% if lang == "ar" %}
                B2B
                {% elif lang == "en" %}
                B2B
                {% endif %}    
                
                </a>
            </li>
            <li class="nav-item" dir="ltr" >
                {% if lang == "ar" %}
                <a  href="{% url 'core:change_lang' %}" dir="ltr">
                    English?
                </a>
                {% elif lang == "en" %}
                
                <a href="{% url 'core:change_lang' %}" dir="ltr">
                    العربية؟
                </a>
                {% endif %}    
                
            </li>

            {% if not user.is_authenticated %}
    <a href="{% url 'core:login' lang %}" class="navbar__act-button">

        {% if lang == "en" %}
        Login
        {% elif lang == "ar" %}

        تسجيل الدخول
        {% endif %}
    </a>
    {% else %}
    <form action="{% url 'core:logout'  %}" method="post">
        {% csrf_token %}
        <input 
        style="color: var(--white);outline:none; background:rgba(0,0,0,1)"
        type="submit" class="navbar__act-button" value="{% if lang == "en" %}Logout{% elif lang == "ar" %}تسجيل الخروج{% endif %}">
    </form>
    {% endif %}
            
        
           
        </ul>
          </div>
        </div>
      </nav>

</div>

</div>