core/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views  import   LogoutView


app_name = "core"

urlpatterns = [
    # func
    path("change_lang/", views.change_lang,                                                 name="change_lang"     ),
    # auth
    path("signup/",      views.signup,                                                      name="signup"          ),
    path("login/",       views.LoginViewSec.as_view(template_name="pages/login.html"),      name="login"           ),
    path("signup/<str:lang>/", views.signup,                                                name="signup"          ),
    path("login/<str:lang>/",  views.LoginViewSec.as_view(template_name="pages/login.html"),name="login"           ),
    path("logout/", LogoutView.as_view(),                                                   name="logout"          ),
    # landing
    path("", views.landing      ,                                                           name="landing"         ),
    path("welcome/<str:lang>/", views.landing      ,                                        name="landing"         ),
    # courses
        # Workshops

    
    # payment
    path("payment/<str:lang>/", views.payment, name="payment"),

    path("payment/", views.payment, name="payment"),
    path("meetups/<str:lang>/", views.meetup, name="meetups"),
    path("meetups/", views.meetup, name="meetups"),
    path("meetups/<str:lang>/<int:pk>/", views.meetup_detail, name="meetup"),
    path("meetups/<str:lang>/", views.meetup_detail, name="meetup"),



    path("send_test_email/", views.send_test_email, name="send_test_email"),


    path("summits/<str:lang>/", views.summit, name="summit"),
    path("summits/", views.summit, name="summit"),
    path("summits/<str:lang>/<int:pk>/", views.summit_detail, name="summit_detail"),
    path("summits/<str:lang>/", views.summit_detail, name="summit_detail"),

    path("speakers/<str:lang>/<int:pk>/", views.speaker, name="speaker"),
    path("speakers/<str:lang>/", views.speaker, name="speaker"),
    path("speakers/", views.speaker, name="speaker"),


    path("check_qr_valid_or_not/<str:uuid>/", views.check_qr_valid_or_not, name="check_qr_valid_or_not"),
    path("check_qr_valid_or_not/", views.check_qr_valid_or_not, name="check_qr_valid_or_not"),

]

courses/urls.py
from django.urls import path
from . import views

app_name = "courses"

urlpatterns = [
    path("courses/<str:lang>/", views.courses_categories_list, name="courses_categories"),
    path("courses/", views.courses_categories_list, name="courses_categories"),
    #
    #course detailes 
    path("courses/<str:lang>/<int:pk>/", views.course_detail, name="course_detail"),
    # video details

    path("courses/<str:lang>/<str:course>/ep/", views.video_detail,                        name="video_detail"),
    path("courses/<str:lang>/<str:course>/ep/<int:pk>/", views.video_detail,                        name="video_detail"),

    path("courses/<str:lang>/<str:course>/", views.course_list_view,                        name="couese_list_view"),
    path("instructor/<str:lang>/<int:pk>/", views.instructor_detail, name="instructor_detail"),
    path("instructor/<str:lang>/", views.instructor_detail, name="instructor_detail"),
    path("instructor/", views.instructor_detail, name="instructor_detail"),

]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
path('admin/', admin.site.urls),
path('', include('core.urls')),
path('', include('courses.urls')),
path('', include('workshops.urls')),
path('ckeditor5/', include('django_ckeditor_5.urls')), 

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models/models.py
from django.db import models
from datetime import datetime
from django.core.validators import FileExtensionValidator
from django.utils.html  import mark_safe
from django.contrib.auth.models   import User

import qrcode
from io import BytesIO
from PIL import Image, ImageDraw
from django.core.files import File
import uuid
import os

from django.urls import reverse
from django.conf import settings

from django_ckeditor_5.fields import CKEditor5Field

class Instructor(models.Model):

    name_ar = models.CharField(max_length=255, verbose_name="اسم المدرس")
    name_en = models.CharField(max_length=255, verbose_name="name in english")
    photo_banner = models.ImageField(upload_to="instructors_photos", blank=True, null=True)
    time_added   = models.DateField(default=datetime.now, editable=False)
    speciality   = models.ForeignKey("CourseCategory", on_delete=models.SET_NULL, null=True, blank=True)
    bio_en        = models.TextField(null=True, blank=True)
    bio_ar        = models.TextField(null=True, blank=True) 

    def show_image(self):
        
        return mark_safe(f"<img style='width:300px;' src='{self.photo_banner.url}'  alt='{self.name_en}' />")
    def more(self):
        return "more"
    show_image.short_description = "photo for him"
    def __str__(self):

        return f"{self.name_ar}"
    class Meta:
        verbose_name        = "المدرس"
        verbose_name_plural = "المدرسين"
        

class CourseCategory(models.Model):
    name_en = models.CharField(max_length=255)
    name_ar = models.CharField(max_length=255)
    banner  = models.ImageField(upload_to="course_categories", blank=True, null=True)


    def more(self):
        return "more"
    def __str__(self):
        return f"{self.name_ar} || {self.name_en}"
    class Meta:
        verbose_name =        "نوع  كورس"
        verbose_name_plural = "انواع الكورسات"
        

class Courses(models.Model):

    
    category   = models.ForeignKey(CourseCategory, on_delete=models.CASCADE)
    banner     = models.ImageField(verbose_name="thumbnail", upload_to="courses_banner_general", blank=True, null=True)
    instructor = models.ForeignKey(Instructor, verbose_name="المدرس", on_delete=models.CASCADE)
    name_ar    = models.CharField(max_length=255, verbose_name="اسم كورس")
    name_en    = models.CharField(max_length=255, verbose_name="اسم الكورس انجليزي")
    description_en= models.TextField(null=True, blank=True)
    description_ar= models.TextField(null=True, blank=True, verbose_name="وصف بالعربي")
    price         = models.FloatField(default=0)
    isonsale      = models.BooleanField(default=False)
    onsale        = models.FloatField(default=0)
    trailer       = models.FileField(upload_to="course_trailer", verbose_name="الفيديو",
    validators=[FileExtensionValidator(
        allowed_extensions=["mp4", "webm", "avi", "AVI", "WebM"])],
    help_text='Allowed : "mp4", "webm", "avi", "AVI", "WebM" ', null=True, blank=True)  

    def __str__(self):
        return f"{self.instructor}|{self.name_ar}"
    class Meta:
        
        verbose_name = "كورس"
        verbose_name_plural = "كورسات"
    def more(self):
        return "انقر للمزيد"
    def show_image(self):
        
        return mark_safe(f"<img style='width:300px;' src='{self.banner.url}'  alt='{self.name_en}' />")
    more.short_description = "انقر للمزيد"
    show_image.short_description = "Thumbnail"

class Ep(models.Model):
    course    = models.ForeignKey(Courses, on_delete=models.CASCADE)
    banner    = models.ImageField(verbose_name="thumbnail", upload_to="courses_banner", blank=True, null=True)
    video     = models.FileField(upload_to="course", verbose_name="الفيديو",
    validators=[FileExtensionValidator(
        allowed_extensions=["mp4", "webm", "avi", "AVI", "WebM"])],
    help_text='Allowed : "mp4", "webm", "avi", "AVI", "WebM" ')
    name_ar   = models.CharField(max_length=255, verbose_name="اسم الحلقة عربي")
    name_en   = models.CharField(max_length=255, verbose_name="اسم الحلقة انجليزي")
    descr_en  = models.TextField(blank=True, null=True, verbose_name="description ")
    descr_ar  = models.TextField(blank=True, null=True, verbose_name="وصف ")
    created_in= models.DateField(default=datetime.now, editable=False)



class Meetup(models.Model):
    
    banner = models.ImageField(upload_to="meetups_banner", blank=True, null=True)
    insctructors = models.ManyToManyField(Instructor    )
    meetupname_en= models.CharField(max_length=255      )
    meetupname_ar= models.CharField(max_length=255      )
    time_added   = models.DateField(default=datetime.now)
    time_event_starts_in = models.DateField(default=datetime.now)
    is_finished  = models.BooleanField(default=False    )
    price         = models.FloatField(default=0)
    isonsale      = models.BooleanField(default=False)
    onsale        = models.FloatField(default=0)
    is_sold      = models.BooleanField(default=False    )
    description_en= models.TextField(null=True, blank=True)
    description_ar= models.TextField(null=True, blank=True, verbose_name="وصف بالعربي")
    def __str__(self):
        return f"{self.meetupname_en} || {self.meetupname_ar}"
    class Meta:
        verbose_name_plural = "Meetups"
        verbose_name        = "Meetup"
    
    def more(self):
        return "more"



class MeetupTicket(models.Model):
     
    user    = models.ForeignKey(User,   on_delete=models.CASCADE, null=True , blank=True)
    meetup  = models.ForeignKey(Meetup, on_delete=models.CASCADE)
    is_used = models.BooleanField(default=False)
    howmany = models.IntegerField(default=0)    

    def __str__(self):
        return f"{self.user.first_name} {self.user.last_name}"
    

    class Meta:
        verbose_name_plural =  "MeetupTickets"
        verbose_name        =  "meetup Ticket"
    


class UserCourses(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    course = models.ForeignKey(Courses, on_delete=models.CASCADE)
    is_completed = models.BooleanField(default=False)
    
    def __str__(self):
        return f"{self.user.first_name} {self.user.last_name}"
    class Meta:
        verbose_name_plural =  "UserCourses"
        verbose_name        =  "UserCourses"




class Speakers(models.Model):
    name_ar = models.CharField(max_length=255, verbose_name="اسم المتحدث")
    name_en = models.CharField(max_length=255, verbose_name="name in english")
    photo_banner = models.ImageField(upload_to="speakers_photos", blank=True, null=True)
    personal_photo = models.ImageField(upload_to="speakers_photos", blank=True, null=True)  
    bio_en        = models.TextField(null=True, blank=True)

    bio_ar        = models.TextField(null=True, blank=True)
    short_bio_en = models.TextField(null=True, blank=True)
    short_bio_ar = models.TextField(null=True, blank=True)
    instgram_link = models.URLField(null=True, blank=True)
    twitter_link = models.URLField(null=True, blank=True)
    facebook_link = models.URLField(null=True, blank=True)
    linkedin_link = models.URLField(null=True, blank=True)

    def __str__(self):
        return f"{self.name_en}"
    
    def more(self):
        return "more"
class Summit(models.Model):

    Speakers = models.ManyToManyField(Speakers, blank=True)
    banner = models.ImageField(upload_to="summits_banner", blank=True, null=True)
    name_ar = models.CharField(max_length=255, verbose_name="اسم المؤتمر")
    name_en = models.CharField(max_length=255, verbose_name="name in english")
    description_en = models.TextField(null=True, blank=True)
    description_ar = models.TextField(null=True, blank=True)
    price = models.FloatField(default=0)
    isonsale = models.BooleanField(default=False)
    onsale = models.FloatField(default=0)
    time_added   = models.DateField(default=datetime.now)
    time_event_starts_in = models.DateField(default=datetime.now)
    is_finished  = models.BooleanField(default=False    )
    trailer = models.FileField(upload_to="summit_trailer", verbose_name="الفيديو",
                               validators=[FileExtensionValidator(
                                   allowed_extensions=["mp4", "webm", "avi", "AVI", "WebM"])],
                               help_text='Allowed : "mp4", "webm", "avi", "AVI", "WebM" ', null=True, blank=True)
    
    def more(self):
        return "more"
    def __str__(self):
        return f"{self.name_en}"
    class Meta:
        verbose_name        = "Summit"
        verbose_name_plural = "Summits"

class SummitTicket(models.Model):
     
    user    = models.ForeignKey(User,   on_delete=models.SET_NULL, null=True , blank=True)

    summit  = models.ForeignKey(Summit, on_delete=models.CASCADE)
    is_used = models.BooleanField(default=False)
    name = models.CharField(max_length=255, null=True, blank=True)
    email = models.CharField(max_length=255, null=True, blank=True)
    phone_number = models.CharField(max_length=255, null=True, blank=True)
    did_he_pay = models.BooleanField(default=False)
    job_title = models.CharField(max_length=255, null=True, blank=True)
    sended_mail = models.BooleanField(default=False)

    choices_for_ticket_type = [
        ("V", "VIP"),
        ("S", "Standard"),
        ]
    ticket_type = models.CharField(choices=choices_for_ticket_type,
        max_length=255, null=True, blank=True)
    # howmany = models.IntegerField(default=0)    
    
    def more(self):
        return "more"
    def __str__(self):
        return f"{self.name or self.pk}"
    

class Messages(models.Model):

    Text       = CKEditor5Field(blank=True)
    created_in = models.DateField(default=datetime.now, editable=False)
    
    def __str__(self):
        return f"{self.Text}"
    class Meta:
        verbose_name        = "Message"
        verbose_name_plural = "Messages"


class QrcodeForTicket(models.Model):

    summitticket = models.ForeignKey(SummitTicket, on_delete=models.CASCADE)

core/models/workshops.py
from django.db import models
from datetime import datetime










class WorkShopsCategory(models.Model):
    name_en = models.CharField(max_length=100)
    name_ar= models.CharField(max_length=100)
    description_en = models.TextField()
    description_ar = models.TextField()
    banner         = models.ImageField(upload_to="workshopscategory_banner", null=True, blank=True)
    def  more(self):
        return "more"

    def __str__(self):
        return self.name_en




class WorkShops(models.Model):

    category = models.ForeignKey(WorkShopsCategory, on_delete=models.CASCADE)

    name_en = models.CharField(max_length=100)
    name_ar= models.CharField(max_length=100)

    description = models.TextField()

    start_date = models.DateField(default=datetime.now)
    end_date = models.DateField()
    location = models.CharField(max_length=100)
    
    def __str__(self):
        return self.name_en
    
    class Meta:
        verbose_name = "Workshops"
        verbose_name_plural = "Workshops"

core/templates/pages/course_detail.html
{% extends "base.html" %}
{% load static %}




{% block title %}{% if lang == 'ar' %} {{course.name_ar}}{% elif lang == 'en' %} {{course.name_en}}{% endif%} {% endblock title %}

{% block extralink %}

    <link rel="stylesheet" href="{% static 'css/pages/course_detail.css' %}">
{% endblock extralink %}



{% block content %}


<main>

    
    <div class="left">

        <img src="{{course.banner.url}}" alt="{{course.name_en}}">
        {% if lang == "en" %}
        <h1>{{course.name_en}}</h1>
        
        {% comment %}  {% endcomment %}
        {% if course.isonsale %}
            <s>Before: {{course.price}} EGP</s>
            <p>After : {{course.onsale}} EGP </p>
        {% else %}
            <p>Price: {{course.price}} EGP</p>

        {% endif %}

        
        {% comment %}  {% endcomment %}
        {% elif lang == "ar" %}
        <h1>{{course.name_ar}}</h1>
        {% if course.isonsale %}
            <s>السعر قبل الخصم : {{course.price}} جنية</s>
            <p>بعد الخصم : {{course.onsale}}  جنية</p>
        {% else %}
            <p>سعر الدورة: {{course.price}} جنية</p>

        {% endif %}

        {% endif %}


        
    </div>

    <div class="right">
        
        {% if lang == "en" %}

            {% if aviable %}
                <a href="{% url 'courses:video_detail' lang course.pk %}" class="payment">View Course</a>
            {% else %}
                <a href="{% url 'core:payment' lang  %}" class="payment"> Purchased</a>

                {% endif %}

        <p> instructor : <a href="{% url "courses:instructor_detail" lang  course.instructor.pk %}" class="instructor" >{{course.instructor.name_en}} </a></p>
        <hr>
        <p>{{course.description_en}}</p>
        <hr>
        
            {% elif lang == "ar" %}
            {% if aviable %}
                <a href="{% url 'courses:video_detail' lang course.pk  %}" class="payment">شاهد الكورس</a>                

            {% else %}
            <a href="{% url 'core:payment' lang  %}" class="payment">شراء</a>
            {% endif %}
            <p> مقدم الدورة : <a href="{% url "courses:instructor_detail" lang  course.instructor.pk %}" class="instructor" >{{course.instructor.name_ar}} </a></p>
            <hr>
            <p>{{course.description_ar}}</p>
            <hr>
        {% endif %}
    </div>

</main>

{% endblock content %}
    

core/templates/pages/courses.html
{% extends "base.html" %}
{% load static %}




{% block title %}{% if lang == 'ar' %}دورات تعليمية{% elif lang == 'en' %}Courses{% endif%} {% endblock title %}

{% block extralink %}

    <link rel="stylesheet" href="{% static 'css/pages/courses.css' %}">
{% endblock extralink %}



{% block content %}


<main class="coursesss" />
{% for courses in data %}
    {% if courses.courses %}
        
    {% if lang == 'en' %}
    <h1 class="categories">{{courses.name_en}}</h1>
    {% elif lang == 'ar' %}
    <h1 class="categories">{{courses.name_ar}}</h1>
    {% endif %}
    <div class="wrapper">
        <div class="container">
            {% for course in courses.courses %}
            <a href='{% url "courses:course_detail" lang  course.pk %}' class="card">
                
                <img src="{{course.banner.url}}" alt="">
                
                <p class="name">{% if lang == "en" %} {{course.name_en}}   {% elif lang  == "ar" %} {{course.name_ar}} {% endif %}</p>
                <p class="price">{% if course.isonsale %}<s>{% endif %} {{course.price}}EGP  {% if course.isonsale %}</s> {{course.onsale}}EGP {% endif %}  </p>
                <p class="description">{% if lang == 'en' %} {{course.description_en|truncatewords:10}} {% elif lang == "ar" %}  {{course.description_ar| truncatechars:60}}   {% endif %}</p>
                
            </a>
            
            
            {% endfor %}
            </div>
            </div>
            
        {% endif %}
    {% endfor %}

    {% comment %} <div class="categories">
        
        {% for category in categories %}
        
        <div class="item">
            
            {% if lang == 'en' %}
            <a href="{% if chosen_course == category.name_en %}{% url 'core:couese_list_view' lang  %}{% else %}{% url 'core:couese_list_view' lang category.name_en %}{% endif%}" {% if chosen_course == category.name_en %}class="avtiveLink" {% else %} class="notchosen" {% endif %}>

                {{category.name_en}}
            </a>
            {% elif lang == 'ar' %}
            <a href="{% if chosen_course == category.name_en%}{% url 'core:couese_list_view' lang  %}{% else %}{% url 'core:couese_list_view' lang category.name_en %}{% endif%}" {% if chosen_course == category.name_en %}class="avtiveLink" {% else %} class="notchosen" {% endif %}>

                {{category.name_ar }}
            </a>
            {% endif %}

        </div>
        {% endfor %}
        <!--  -->

      


    </div> {% endcomment %}
</main>


{% endblock content %}
    

core/templates/pages/landing1.html
{% extends "base.html" %}
{% load static %}

{% block title %}
{% if lang == "ar" %}
الرئيسية


{% elif lang == "en" %}
Home
{% endif %}
{% endblock title %}

{% block extralink %}
{% endblock extralink %}

{% block content %}

<div class="hero">
    <img src="{% static '/image/Trapezoidal.png' %}" alt="" class="background">
    <div class="hero__content">
        <div class="hero__image">
            <img src="{% static '/image/logo_lg.png' %}" alt="" class="logo">
        </div>
        <div class="hero__text">
            <h1 dir="rtl">
                {% if lang == "ar" %}
                أطلق العنان لإمكاناتك <br>
                من خلال دوراتنا المتنوعة

                {% elif lang == "en" %}
                Unleash your potential 
                <br>
                Through our various courses

                {% endif %}
            </h1>
            <p dir="rtl">
                {% if lang == "en" %}
                On our educational platform, we offer a wide range of courses in different fields such as
                Languages, programming, graphic design, marketing, etc. Whether you are a beginner or an expert,
                Our courses are designed to help you enhance your skills and achieve your goals.

     {% elif lang == "ar" %}

     نقدم في منصتنا التعليمية مجموعة واسعة من الدورات في مجالات مختلفة مثل 
     اللغات والبرمجة والتصميم الجرافيكي والتسويق وغيرها. سواء كنت مبتدئًا أو خبيرًا، 
     فقد تم تصميم دوراتنا لمساعدتك على تعزيز مهاراتك وتحقيق أهدافك.
     {% endif %}
            </p>
            <div class="hero__buttons" dir="rtl">
                {% if not user.is_authenticated %}

                <a href="{% url 'core:signup' lang %}" class="register-button"
                dir="auto"                                                              
                >
                {% if lang == "ar" %}
                  

                اشترك الان !

                {% elif lang == "en" %}
                Signup !
                {% endif %}
            </a>
                <a href="{% url 'core:login' lang %}" class="login-button">
                {% if lang == "ar" %}
                تسجيل الدخول
                  
                {% elif lang == "en" %}
                Login
                {% endif %}
                
                </a>
                {% endif %}
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    function zoom() {
        document.body.style.zoom = "75%" 
    }
</script>

<body onload="zoom()">
{% endblock content %}

{% block extrascript %}
{% endblock extrascript %}

core/templates/pages/payment.html
{% extends "base.html" %}
{% load static %}




{% block title %}{% if lang == 'ar' %} {{course.name_ar}}{% elif lang == 'en' %} {{course.name_en}}{% endif%} {% endblock title %}

{% block extralink %}

    <link rel="stylesheet" href="{% static 'css/pages/payment.css' %}">
{% endblock extralink %}



{% block content %}

{% endblock content %}
    

core/templates/pages/signup.html
{% extends "base.html" %}
{% load static %}

{% block title %}{% if lang == "ar" %}انضم الينا{% elif lang == "en" %}Join us{% endif %}{% endblock title %}

{% block extralink %}
<link rel="stylesheet" href="{% static 'css/pages/signup.css' %}">
{% endblock extralink %}

{% block content %}
<div class="wrapper">

    <div class="right__word">
        {% if lang == "en" %}
          
        Join us now
        {% elif lang == "ar" %}

        أنضم الينا الأن
        {% endif %}

    </div>
    <div class="line">
        <img src="{% static 'image/line1.png' %}" alt="">
        <img src="{% static 'image/line2.png' %}" alt="">
        
    </div>
    <div class="line_2">
        <img src="{% static 'image/line1.png' %}" alt="">
        <img src="{% static 'image/line2.png' %}" alt="">
        
    </div>
    
    
    <main id="main__content">
        <form method="post" id="login_form">
            {% csrf_token %}
            
            {% if form.errors %}
            <div id="messages" >
                <div id="close__message">x</div>
                {% if lang == "ar" %}

                تأكد من اسم المستخدم وكلمة المرور
                {% elif lang == "en" %}
                  Make sure that the password and username is correct! 
                {% endif %}

            </div>
            {% endif %}
            <div class="username field">
                <label for="id_username">
                    {% if lang == "en" %}
                      
                    Username : 
                    {% elif lang == "ar" %}
                    :اسم المستخدم

                    {% endif %}
                </label>
                <input type="text" name="username" id="id_username" placeholder="{% if lang == 'ar' %}اسم المستخدم{% elif lang == 'en' %}Username{% endif %}" required>
                
            </div>
            <div class="field">
                <label for="id_email">
                    {% if lang == "ar" %}

                        :الايميل
                    {% elif lang == "en" %}
                      Email:
                    {% endif %}
                </label>
                <input type="email" name="email" id="id_email" placeholder="{% if lang == "ar" %}الايميل{% elif lang == "en" %}Email:{% endif %}" required>
               
            </div>
            <div class="password field">
                <label for="id_password">
                    {% if lang == "en" %}
                      
                    Password:
                    {% elif lang == "ar" %}

                    :كلمة المرور
                    {% endif %}
                </label>
                <input type="password" name="password1" id="id_password1" placeholder="{% if lang == "en" %}Password:{% elif lang == "ar" %}:كلمة المرور{% endif %}" required>
               
            </div>
            
            <div class="password field">
                <label for="id_password">
                    {% if lang == "ar" %}

                    تأكيد كلمة المرور:
                    {% elif lang == "en" %}
                      Confirm Passoword:
                    {% endif %}
                </label>
                <input type="password" name="password2" id="id_password2" placeholder="{% if lang == 'ar' %}تأكيد كلمة المرور{% elif lang == 'en' %}Confirm password{% endif %}" required>
               
            </div>

            <button type="submit" >
                
                {% if lang == "ar" %}
                  تسجيل
                {% elif lang == "en" %}
                Submit
                {% endif %}
                
            
            </button>



            <div class="down_form">
                {% if lang == "ar"  %}
                  
                <span>
                    لديك حساب بالفعل؟ 
                    
                </span>
                
                <a href="{% url 'core:login' lang %}">
                    انقر هنا
                </a>
                {% elif lang == "en" %}
                <a href="{% url 'core:login' lang %}">
                    Login</a>

                <span>

                    Have an account?
                </span>
                
                {% endif %}
            </div>

        </form>
    </main>
</div>
{% comment %} 
<script>
    let xButton = document.getElementById("close__message");
    let message = document.getElementById("messages");

    xButton.addEventListener("click", ()=>{
        message.remove()
    })

</script> {% endcomment %}
    {% endblock content %}
    

core/templates/pages/watch_video.html
{% extends "base.html" %}
{% load static %}
{% block title %}{% if lang == 'ar' %} {{video.name_ar}}{% elif lang == 'en' %} {{video.name_en}}{% endif%} {% endblock title %}


{% block extralink %}
<link rel="stylesheet" href="{% static 'css/pages/video_detail.css' %}">
<link rel="stylesheet" href="{% static 'css/pages/courses.css' %}">
{% endblock extralink %}
{% block content %}
<main>
    
    <div class="video-wrapper">
        {% if lang == "en" %}
        <h1>{{course.name_en}}</h1>
        <h1>{{video.name_en}}</h1>

        {% elif lang  == "ar" %}
        <h1>{{course.name_ar}}</h1>
        <h1>{{video.name_ar}}</h1>
        {% endif %}
        <div class="video-container">   
            <video   controls />
                <source src="{{video.video.url}}" type="video/mp4">
                Your browser does not support the video tag.
            </video>
        </div>
        
        <p>

            {% if lang == "en" %}
                {{video.descr_en}}
                <p> instructor : <a href="{% url "courses:instructor_detail" lang  course.instructor.pk %}" class="instructor" >{{course.instructor.name_en}} </a></p>
            {% elif lang  == "ar" %}
                {{video.descr_ar}}
                <p> مقدم الدورة : <a href="{% url "courses:instructor_detail" lang  course.instructor.pk %}" class="instructor" >{{course.instructor.name_ar}} </a></p>

            {% endif %}
        </p>
    </div>

<hr>
    <div class="wrapper">
        <div class="container">
        {% for vid in others %}
        <a href='{% url "courses:video_detail" lang course.pk  vid.pk %}' class="card">
    
            <img src="{{vid.banner.url}}" alt="{{vid.name_en}}">
            
            <p class="name">{% if lang == "en" %} {{vid.name_en}}   {% elif lang  == "ar" %} {{vid.name_ar}} {% endif %}</p>

            <p class="description">{% if lang == 'en' %} {{vid.descr_ar|truncatewords:10}} {% elif lang == "ar" %}  {{vid.descr_ar| truncatechars:60}}   {% endif %}</p>
            
        </a>
    
    
        {% endfor %}
        </div>
    </div>

</main>


{% endblock content %}